//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC_Database_First_CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class depdesempEntities : DbContext
    {
        public depdesempEntities()
            : base("name=depdesempEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbdep> tbdeps { get; set; }
        public virtual DbSet<tbdsg> tbdsgs { get; set; }
        public virtual DbSet<tbemployee> tbemployees { get; set; }
    }
}
