//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC_Database_First_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbemployee
    {
        public int empno { get; set; }
        public string ename { get; set; }
        public string eadd { get; set; }
        public Nullable<int> esal { get; set; }
        public Nullable<int> edno { get; set; }
        public Nullable<int> edsgcod { get; set; }
    
        public virtual tbdep tbdep { get; set; }
        public virtual tbdsg tbdsg { get; set; }
    }
}
